# Generated by Django 5.2.3 on 2025-06-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
