# Generated by Django 5.2.4 on 2025-07-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_otptoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otptoken',
            old_name='otp_expires',
            new_name='otp_expires_at',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='aa478c', max_length=6),
        ),
    ]
